version: "3.9"
services:
  webapp:
    image: frenchben/flash:head
    ports: 
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app
  cache:
    image: varnish:7.1
    ports: 
      - "8080:80"
    networks:
      - app
    volumes:
      - type: bind
        source: ./varnish/default.vcl
        target: /etc/varnish/default.vcl
        read_only: true
networks:
  app:
