version: "3.9"
services:
  webapp:
    image: frenchben/flash:head
    ports: 
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - varnish-net
      - nginx-net
      - hammer-net
  varnish-cache:
    image: varnish:7.1
    ports: 
      - "8080:80"
    networks:
      - varnish-net
      - hammer-net
    volumes:
      - type: bind
        source: ./cache-conf/varnish-default.vcl
        target: /etc/varnish/default.vcl
        read_only: true
  nginx-cache:
    image: nginx:1.23
    ports: 
      - "8081:80"
    networks:
      - nginx-net
      - hammer-net
    volumes:
      - type: bind
        source: ./cache-conf/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
networks:
  varnish-net:
  nginx-net:
  hammer-net: